#!/bin/sh
set -o errexit

# Dependencies
# ------------
#
# On OSX and Linux:
#
#     sudo easy_install pip
#     sudo pip install LinkChecker
#
script/generate-docs
lines_changed_count=$(git diff | wc -l)
if [ $lines_changed_count -ne 0 ]; then
  echo "[fatal] Lines show as changed.  This likely means the schemata and generated docs are out of sync."
  exit 1
fi
bundle exec jekyll build
linkchecker '_site/index.html'
