#!/bin/sh
set -o errexit

# Dependencies
# ------------
#
# On OSX and Linux:
#
#     sudo easy_install pip
#     sudo pip install LinkChecker
#
script/generate-docs
git diff
bundle exec jekyll build
linkchecker '_site/index.html'
